//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleonApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalleonApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string ActionCancelText {
            get {
                return ResourceManager.GetString("ActionCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ActionOKText {
            get {
                return ResourceManager.GetString("ActionOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string AddContactText {
            get {
                return ResourceManager.GetString("AddContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressHint {
            get {
                return ResourceManager.GetString("AddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryHint {
            get {
                return ResourceManager.GetString("CategoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityHint {
            get {
                return ResourceManager.GetString("CityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        public static string ClearCustomerText {
            get {
                return ResourceManager.GetString("ClearCustomerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactNameHint {
            get {
                return ResourceManager.GetString("ContactNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ContactNameTitle {
            get {
                return ResourceManager.GetString("ContactNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contact List.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryHint {
            get {
                return ResourceManager.GetString("CountryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string CustomerInfoTitle {
            get {
                return ResourceManager.GetString("CustomerInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Contact.
        /// </summary>
        public static string DialogAddNewContactTitle {
            get {
                return ResourceManager.GetString("DialogAddNewContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no sync folder selected..
        /// </summary>
        public static string DownloadFileErrorText1 {
            get {
                return ResourceManager.GetString("DownloadFileErrorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EditContactText {
            get {
                return ResourceManager.GetString("EditContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameHint {
            get {
                return ResourceManager.GetString("FirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity No.
        /// </summary>
        public static string IdentityHint {
            get {
                return ResourceManager.GetString("IdentityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be at least 2 chars..
        /// </summary>
        public static string InvalidAddressText {
            get {
                return ResourceManager.GetString("InvalidAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name must be at least 2 chars.
        /// </summary>
        public static string InvalidContactNameText {
            get {
                return ResourceManager.GetString("InvalidContactNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 3 chars.
        /// </summary>
        public static string InvalidCustomerNameText {
            get {
                return ResourceManager.GetString("InvalidCustomerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname must be at least 2 chars.
        /// </summary>
        public static string InvalidCustomerSurnameText {
            get {
                return ResourceManager.GetString("InvalidCustomerSurnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such directory exists..
        /// </summary>
        public static string InvalidDirectoryText {
            get {
                return ResourceManager.GetString("InvalidDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idnetity must be 11 digit.
        /// </summary>
        public static string InvalidIdentityText {
            get {
                return ResourceManager.GetString("InvalidIdentityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        public static string InvalidOptionText {
            get {
                return ResourceManager.GetString("InvalidOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 chars..
        /// </summary>
        public static string InvalidPasswordText {
            get {
                return ResourceManager.GetString("InvalidPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must be at least 10 digit, start with area code without 0.
        /// </summary>
        public static string InvalidPhoneText {
            get {
                return ResourceManager.GetString("InvalidPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName must be e-mail format..
        /// </summary>
        public static string InvalidUserNameText {
            get {
                return ResourceManager.GetString("InvalidUserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameHint {
            get {
                return ResourceManager.GetString("LastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleNameHint {
            get {
                return ResourceManager.GetString("MiddleNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneHint {
            get {
                return ResourceManager.GetString("PhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores last successfull login for future login usage..
        /// </summary>
        public static string PreferenceRememberMeDescription {
            get {
                return ResourceManager.GetString("PreferenceRememberMeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string PreferenceRememberMeTitle {
            get {
                return ResourceManager.GetString("PreferenceRememberMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts sync when a file modification occured in the prefered directory..
        /// </summary>
        public static string PreferenceSyncDescription {
            get {
                return ResourceManager.GetString("PreferenceSyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory where your cloud files will sync and remain in..
        /// </summary>
        public static string PreferenceSyncDirectoryDescription {
            get {
                return ResourceManager.GetString("PreferenceSyncDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Sync Directory.
        /// </summary>
        public static string PreferenceSyncDirectoryTitle {
            get {
                return ResourceManager.GetString("PreferenceSyncDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Sync.
        /// </summary>
        public static string PreferenceSyncTitle {
            get {
                return ResourceManager.GetString("PreferenceSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory where your tooling results on files will we stored and you can add those your cloud acc easily..
        /// </summary>
        public static string PreferenceToolsDirectoryDescription {
            get {
                return ResourceManager.GetString("PreferenceToolsDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Directory.
        /// </summary>
        public static string PreferenceToolsDirectoryTitle {
            get {
                return ResourceManager.GetString("PreferenceToolsDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESS.
        /// </summary>
        public static string ProcessButtonText {
            get {
                return ResourceManager.GetString("ProcessButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for a while....
        /// </summary>
        public static string ProgressDialogLoadingText {
            get {
                return ResourceManager.GetString("ProgressDialogLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMeCheckBoxText {
            get {
                return ResourceManager.GetString("RememberMeCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string RemoveContactText {
            get {
                return ResourceManager.GetString("RemoveContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete Remote File..
        /// </summary>
        public static string RemoveFileErrorText {
            get {
                return ResourceManager.GetString("RemoveFileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File is successful..
        /// </summary>
        public static string RemoveFileSuccess {
            get {
                return ResourceManager.GetString("RemoveFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is saved in system, successfully..
        /// </summary>
        public static string SaveCustomerSuccessText {
            get {
                return ResourceManager.GetString("SaveCustomerSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SaveCustomerText {
            get {
                return ResourceManager.GetString("SaveCustomerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW IN DIRECTORY.
        /// </summary>
        public static string ShowInDirectoryButtonText {
            get {
                return ResourceManager.GetString("ShowInDirectoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Directory.
        /// </summary>
        public static string SyncDirectoryHint {
            get {
                return ResourceManager.GetString("SyncDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Directory.
        /// </summary>
        public static string ToolsDirectoryHint {
            get {
                return ResourceManager.GetString("ToolsDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpeced error occured. Try later again..
        /// </summary>
        public static string UnexpectedErrorText {
            get {
                return ResourceManager.GetString("UnexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop Files.
        /// </summary>
        public static string UploadHereText {
            get {
                return ResourceManager.GetString("UploadHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameHint {
            get {
                return ResourceManager.GetString("UserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not see file that does not downloaded..
        /// </summary>
        public static string ViewFileErrorText1 {
            get {
                return ResourceManager.GetString("ViewFileErrorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File you are looking for deleted..
        /// </summary>
        public static string ViewFileErrorText2 {
            get {
                return ResourceManager.GetString("ViewFileErrorText2", resourceCulture);
            }
        }
    }
}
